layout_spectrum: 0.09148936
typography_spectrum: 0.4255319
color:
  lightness: 0.8917863
  brandStrength: 1
  saturation: 0.1567692
  rhythmicContrast: 0.6226183
  brandColors:
    - '#FFFFFF'
    - '#393939'
    - '#2C8FB5'
    - '#1D9175'
    - '#317FB5'
name: 'Utopia Vision '
