layout_spectrum: 1
name: 'Utopia Vision '
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 1
  lightness: 0.8917863
  saturation: 0.1567692
  rhythmicContrast: 0.6226183
  brandColors:
    - '#2495C8'
    - '#0F957C'
    - '#19B1C0'
    - '#000101'
    - '#031310'
typography_spectrum: 0.4255319
